language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script: cd packages/raccoon-city-ui
script:
- cd ../raccoon-city-graphql
- yarn
- yarn run build
deploy:
  provider: heroku
  local_dir: packages/raccoon-city-graphql/dist
  on:
    branch: master
  api_key:
    secure: VYb6LX+Q9f5kp1TwJG7D5MUqxT7dBHQmzHtuKpGSS5SFd22SDxMo1pIzCIUIk1LgxonOMgQdF4CKRAmzZYfhjd0iAvZMjdTaME+Kin+ZhjkJMz7CMy/UiuQfnJmhua3aQxxJ5M/fkdfMyb3OA7NWmnIV83EMvdGcVGwPaUoD/BSOnpAEDHDlqSnBFXUQ1AfHO+yQTMnaecIKiapkO7SKBpansN5v3ROMhDGdtzD67bbF+uHyIMZYo+07EjZzU9Spvck2QWcAXJajBVaGT+izuz4DF9IjMSYtJxPUEdbkUVNRMxhAucHFUD6p5VQavjIEtP5BmAjlYUhrhkz3fHfasJcDBpgRVWeOJldgXFIyUcuKl+Yle719MBoQ2fW4pBCTQo+R/z6glwF8ULrisZZBtkwwtZJU/mOrJlYLBj4JsBRYWTvS3PL9vPxe1wproRUcfzu3RRk/Z/sasC/wrLW4OtiO7X4ChozSo4eWsk8yjCwlwyRu0Jd+kKpqRopmVmor2Eau4v+MQzzDK5Ww7krc/eqcRAhdWUye0VMXZTpr8oEl0W4n6+7Wqh9OxY/K1V1aeip6y+WdvYQG1s1hgcCpA0aYY2fakrX5O1IqAKXCae6udU0H0nRNRq88ZTROfeGOD3HYsIQOVYjaHICnAmgku8eOAjbT22eQr4zjFdDjOwU=
