language: node_js
node_js:
  - stable
cache:
  directories:
    - packages/raccoon-city-ui/node_modules
    - packages/raccoon-city-graphql/node_modules
before_script: cd packages/raccoon-city-ui
script:
  - yarn
  - yarn run build
  - cd ../raccoon-city-graphql
  - yarn
  - yarn run build
  - cd ../../
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: raccoon-city-bucket
    upload-dir: raccoon-city-ui-dev
    local_dir: packages/raccoon-city-ui/build
    acl: public_read
    on:
      branch: master

