language: node_js
node_js:
  - stable
cache:
  directories:
    - packages/raccoon-city-ui/node_modules
    - packages/raccoon-city-graphql/node_modules
before_cache:
  - pip install --user awscli
jobs:
  include:
    - stage: ui
      env:
        - REACT_APP_GRAPHQL_URL=$GRAPHQL_URL
      script:
        - cd packages/raccoon-city-ui
        - yarn
        - yarn run build
      deploy:
        - provider: script
          script: ~/.local/bin/aws s3 sync build s3://raccoon-city-bucket/raccoon-city-ui-dev --region=eu-central-1 --delete
          skip_cleanup: true
          on:
            branch: master
        - provider: s3
          skip_cleanup: true
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: raccoon-city-bucket
          upload-dir: raccoon-city-ui-dev
          local_dir: build
          region: eu-central-1
          on:
            branch: master
    - stage: backend
      script:
        - cd packages/raccoon-city-graphql
        - yarn
        - yarn run build
        - zip -r latest *
        - mkdir -p dpl_cd_upload
        - mv latest.zip dpl_cd_upload/latest.zip
      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          local_dir: dpl_cd_upload
          skip_cleanup: true
          on:
            branch: master
          region: eu-central-1
          bucket: raccoon-city-bucket
          upload-dir: raccoon-city-ui-gql
        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: raccoon-city-bucket
          key: latest.zip
          bundle_type: zip
          file_exists_behavior: overwrite
          application: raccooncity
          deployment_group: raccooncity-deployment-group
          region: eu-central-1
          on:
            branch: master
        - provider: heroku
          on:
            branch: develop
          app: raccoon-city-test
          local_dir: build
          api_key:
            secure: xPXL3GvZcpzib9q9sJaMyNz9E4oMrGTk1xbfqO8WZkiwCvsd2987biVt0r0eD31Idtp+QbOC8P2fogzo3m6GN7SJO6m+SBJm3eqSjgzyDTx4fqgCXaWBFNRfv9VcoB7RfwDjiNlz9LI+7NCeN+Yv0b1gTbt9aXoGDI3B8dWbSsv2ZOrwA46Bi9css8iKzC5L7MnDiRteJnUBQq7AVIKwQf3CFdq4OaCZX63bx1NT9UNqcxaYvM/75N8H+l2rczNyVbwxLTqj0VfUnCfnu4+IvwQFUBWsxydWtiUJlwUcSEr6K5W8qcw1SU0p5BSdvGJNlsu2G+wC82csOEeyrzDcLZL31mbUC8r2umDatiYyLeHu0+T6JP/S+wfe2VK7vLQUIdL5F784i9XJKiUlzrA8tw7Mo8Bo1SbsmshH0LO4NEHHOFtRaP5ZHFzNsUN+4ORG+koN2+CNnvXuxw+O/E+adg3EeGPmqHMlms5n16/S07sQ02T37xaAeaC/NVe3cvEa7dCbWa5t/VZtp6XKyI3z5IADGNm/CnoHfrnAqf6uLFTmncR8G/wERiOEX3uhbMrEqi61yUH+yRS7XRYwzTK6U81S+sRKFKqeORFFS4FwMZ/rt99zWax/Wpt7MVVS8y2J3SM0Aa8OUfIQnmqP+PDGer/O8It0Edg3GfcMGRc0PCQ=

