language: node_js
node_js:
  - stable
before_cache:
  - pip install --user awscli
cache:
  directories:
    - packages/raccoon-city-ui/node_modules
    - packages/raccoon-city-graphql/node_modules
before_script: cd packages/raccoon-city-ui
script:
  - yarn
  - yarn run build
  - cd ../raccoon-city-graphql
  - yarn
  - yarn run build
deploy:
  - provider: script
    skip_cleanup: true
    local_dir: packages/raccoon-city-ui
    script:
      - export BUCKET=raccon-city-bucket LOCAL_DIR=build
      - export PATH=./node_modules/.bin:$PATH
      - export UPLOAD_DIR=development
      - awss3-deploy
    on:
      branch: master

