language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script: cd packages/raccoon-city-ui
script:
- cd ../raccoon-city-graphql
- yarn
- yarn run build
deploy:
  provider: heroku
  local_dir: packages/raccoon-city-graphql/dist
  on:
    branch: master
  api_key:
    secure: C461gS1kZx2DgQhsoflOr3oEpEaitz7TXrQpH9iLjD7FP9ImHBX9VGRCIvjKcIeFVPlQD4jEgkvEJEJRCeeqM/6oOhDYv2xzCZQR2DRmJrctlphp3mA8Dsl1XVpD54HPOirK8Nc+VHb7xZF66pAATO2UFjgNbx6Oe1HSxxnZSYu201Rh6whpUXTtzA99fStV18VyBbejV5eui76acync5Wm5ucrEyK29erVJFLqjychzLlpRwYSuGhvrKSrPWdSezY7TDsud4bKIj+/bgC7ggEJfASeZ5n/Lsi3QcmO7/d5JfHMOvMFIKOrCOihk+g0hH/1H6wMviGXJ7rTs6titMbjsUBx+dWColq0eC2UusLeZ/O9Xbsg3A9qIiMeS3lRO1xzy7UjCKNmIKWqBUYQrYAwlk1ag6UxLgNOeclSqT6RGhKRRbyvVZ9cp+lQr5UdG5ipcPDrZ3koeeI6Le8ivnxBkVJnlx0n3X2I9J2ztgpHwGuPXfTxCKxiGZN/z46jaLxVYHV/E437KaWEezToQ0ue/3mGIiQDOk8XZgafEe79P1v3/zGVr9xYTvXS0K1ZSaOsV0S2lXWAhX+5EHBun0s6Bi2PIkWyvQtf4FPzEnzMrHi1+qAYmPktKbeYldJmdihn3TmUJv7qeHEDRLv7QanhUgXbNo5uoPLAB9+x2Nuo=
