language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_script: cd packages/raccoon-constants-ui
script:
  - yarn
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: packages/raccoon-constants-ui/build
  on:
    branch: master
