language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script: cd packages/raccoon-city-ui
script:
- cd ../raccoon-city-graphql
- yarn
- yarn run build
deploy:
  provider: heroku
  local_dir: packages/raccoon-city-graphql/dist
  on:
    branch: master
  api_key:
    secure: 4871e37c-8974-4c6a-88dc-de57c6e6a285
