version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/raccoon-city-graphql
hooks:
  ApplicationStop:
    - location: bin/remove_archives.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: bin/start_nodeserver.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: bin/MonitorService.sh
      timeout: 3600
      runas: root
